# make app-secret-env based on redis inside create variables user_name and password which you take from the secret mysecret of the corresponding keys uname and pass

apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
    - name: user_name
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: uname
    - name: password
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: pass
  restartPolicy: Never
