# make the kbot-livenessProbe from gcr.io/tidy-shard-382112/kbot work on port 8080 with a maximum of 5 errors

apiVersion: v1
kind: Pod
metadata:
  name: kbot-livenessProbe
spec:
  containers:
  - name: kbot
    image: gcr.io/tidy-shard-382112/kbot
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 5

