# "make a pod from gcr.io/tidy-shard-382112/kbot with the name kbot the application runs on port 8080"

apiVersion: v1
kind: Pod
metadata:
  name: kbot
spec:
  containers:
  - name: kbot-container
    image: gcr.io/tidy-shard-382112/kbot
    ports:
    - containerPort: 8080
