name: KBOT-CICD

on: push

env:
  ARCH: amd64
  REGISTRY: ghcr.io/${{ github.repository }}
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
                          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: GitHub Contener login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build&Push
        run: make image push clean ARCH=$ARCH REGISTRY=$REGISTR
      - name: Clean
        run: make clean ARCH=$ARCH
      
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(ARCH)' helm/values.yaml
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update version $VERSION"
        git push